# SPDX-FileCopyrightText: 2024 Nextcloud GmbH and Nextcloud contributors
# SPDX-License-Identifier: AGPL-3.0-or-later
version = 1
SPDX-PackageName = "files_emailviewer"
SPDX-PackageSupplier = "Nextcloud <info@nextcloud.com>"
SPDX-PackageDownloadLocation = "https://github.com/nextcloud/files_emailviewer"

[[annotations]]
path = [
	"l10n/**.js",
	"l10n/**.json",
]
precedence = "aggregate"
SPDX-FileCopyrightText = "2024 Nextcloud GmbH and Nextcloud contributors"
SPDX-License-Identifier = "AGPL-3.0-or-later"

[[annotations]]
path = [
	"composer.json",
	"composer.lock",
	"package-lock.json",
	"package.json",
	"tests/psalm-baseline.xml",
	"vendor-bin/**/composer.json",
	"vendor-bin/**/composer.lock",
	'.l10nignore',
	'.tx/config',
]
precedence = "aggregate"
SPDX-FileCopyrightText = "none"
SPDX-License-Identifier = "CC0-1.0"
