OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "مستعرض البريد الالكتروني",
    "Enable the php function proc_open to run the email-to-pdf converter." : "تمكين دالة \"بي إتش بي\" proc_open  من إجراء التحول من إيميل إلى \"بي دي إف\".",
    "Java is required to run the email-to-pdf converter." : "الجافا ضرورية لإجراء التحويل من إيميل إلى \"بي دي إف\".",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "قم رجاءً بتثبيت https://github.com/nickrussler/email-to-pdf-converter و قم بتعيين المسار عبر `%s`",
    "View .msg and .eml files" : "عرض ملفات .msg و .eml  ",
    "<h4>Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.</h4>\n\n<h5>Requirements</h5>\n<ul>\n\t<li>Nextcloud 28 or newer</li>\n\t<li>PDF Viewer for Nextcloud</li>\n\t<li>PHP proc_open</li>\n\t<li>OpenJDK</li>\n\t<li>wkhtmltopdf (https://wkhtmltopdf.org/)</li>\n\t<li>Email to PDF Converter (https://github.com/nickrussler/email-to-pdf-converter)</li>\n</ul>\n\n<h5>Installation</h5>\n<ul>\n\t<li>Download and enable files_emailviewer</li>\n\t<li>Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it</li>\n\t<li>Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`</li>\n\t<li>Upload a .msg or .eml file and view it directly in Nextcloud 🙌</li>\n</ul>\n\n<h5>Outgoing connections</h5>\n<ul>\n\t<li>If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections</li>\n\t<li>The current version does not consider Nextcloud's proxy configuration but should follow the system default</li>\n</ul>" : "\t<h4>يقوم عارض الإيميل email Viewer بمكاملة أداة تحويل الإيميل إلى \"بي دي إف\" مع نكست كلاود بما يُمكِّنك من مشاهدة ملفات .msg و .eml.</h4>\n\n<h5>المتطلبات</h5>\n<ul>\n\t<li>الإصدار 28 من نكست كلاود فما أعلى</li>\n\t<li>عارض نكست كلاود لملفات \"بي دي إف\"</li>\n\t<li>PHP proc_open</li>\n\t<li>OpenJDK</li>\n\t<li>wkhtmltopdf (https://wkhtmltopdf.org/)</li>\n\t<li>أداة تحويل البريد الإلكتروني إلى ملفات \"بي دي إف\"   (https://github.com/nickrussler/email-to-pdf-converter)</li>\n</ul>\n\n<h5>التثبيت</h5>\n<ul>\n\t<li>قم بتنزيل و تثبيت ملفات _emailviewer</li>\n\t<li>قم بحفظ نسخة من ملفات المحول على الخادوم بحيث يمكن لنكست كلاود الوصول إليها </li>\n\t<li>قم بتعيين مسار المحول بالأمر السطري:  `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`</li> \n\t<li>قم برفع ملفات .msg و .eml و سيمكنك مشاهدتها على نكست كلاود 🙌 </li>  \t\n</ul>\n\n<h5>الارتباطات الصادرة</h5>\n<ul>\n\t<li>إذا كان الإيميل يحتوي على صور من مصادر خارجية, سيقوم المحول بتنزيلها من المصادر الخارجية. الإصدار الحالي لا يراعي إعدادات وكيل نكست كلاود لكنه سيتبع الإعدادات التلقائية للنظام </li>\n </ul>"
},
"nplurals=6; plural=n==0 ? 0 : n==1 ? 1 : n==2 ? 2 : n%100>=3 && n%100<=10 ? 3 : n%100>=11 && n%100<=99 ? 4 : 5;");
