OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "Πρόγραμμα προβολής Email",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Ενεργοποιήστε τη λειτουργία proc_open της PHP για να εκτελέσετε τον μετατροπέα email-to-pdf.",
    "Java is required to run the email-to-pdf converter." : "Απαιτείται Java για την εκτέλεση του μετατροπέα email-to-pdf.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Εγκαταστήστε το https://github.com/nickrussler/email-to-pdf-converter και ορίστε τη διαδρομή μέσω `%s`",
    "View .msg and .eml files" : "Προβολή αρχείων .msg και .eml",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### Το Email Viewer ενσωματώνει τον εξαιρετικό Μετατροπέα Email σε PDF στο Nextcloud, επιτρέποντάς σας να προβάλλετε αρχεία .msg και .eml.\n\n#### Απαιτήσεις\n\n- Nextcloud 28 ή νεότερη\n- Viewer και PDF Viewer για Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (απαιτεί OpenJDK και [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Εγκατάσταση\n\n- Κατεβάστε και ενεργοποιήστε το files_emailviewer\n- Αποθηκεύστε ένα αντίγραφο του Email to PDF Converter στον διακομιστή, διασφαλίζοντας ότι το Nextcloud έχει πρόσβαση σε αυτό\n- Ορίστε τη διαδρομή προς τον Email to PDF Converter μέσω `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Μεταφορτώστε ένα αρχείο .msg ή .eml και προβάλλετε το απευθείας στο Nextcloud 🙌\n\n#### Εξερχόμενες συνδέσεις\n\n- Εάν το email περιέχει εικόνες από εξωτερικές πηγές, ο Μετατροπέας Email σε PDF θα κατεβάσει τις εικόνες, απαιτώντας εξωτερικές συνδέσεις\n- Η τρέχουσα έκδοση δεν λαμβάνει υπόψη τη διαμόρφωση διακομιστή μεσολάβησης του Nextcloud, αλλά θα πρέπει να ακολουθεί την προεπιλογή του συστήματος"
},
"nplurals=2; plural=(n != 1);");
