OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "E-posta ikustailea",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Gaitu proc_open php funtzioa posta elektronikotik pdf-ra bihurgailua exekutatzeko.",
    "Java is required to run the email-to-pdf converter." : "Java beharrezkoa da posta elektronikotik pdf-ra bihurgailua exekutatzeko.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Mesedez, instalatu https://github.com/nickrussler/email-to-pdf-converter eta ezarri bidea  `%s` bidez",
    "View .msg and .eml files" : "Ikusi .msg eta .eml fitxategiak",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- PDF Viewer for Nextcloud\n- PHP proc_open\n- OpenJDK\n- [wkhtmltopdf](https://wkhtmltopdf.org/)\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter)\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### E-posta ikustaileak Email to PDF Converter bikaina integratzen du Nextcloud-en, .msg eta .eml fitxategiak ikusteko aukera emanez.\n\n#### Baldintzak\n\n- Nextcloud 28 edo berriagoa\n- Nextcloud-erako PDF ikustailea\n- PHP proc_open\n- OpenJDK\n- [wkhtmltopdf](https://wkhtmltopdf.org/)\n- [Posta elektronikoa PDF bihurgailua] (https://github.com/nickrussler/email-to-pdf-converter)\n\n#### Instalazioa\n\n- Deskargatu eta gaitu files_emailviewer\n- Gorde Email to PDF Converter-en kopia bat zerbitzarian, Nextcloud-ek sarbidea duela ziurtatuz\n- Ezarri bidea Email to PDF Converter-en `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Kargatu .msg edo .eml fitxategi bat eta ikusi zuzenean Nextcloud-en 🙌\n\n#### Irteerako konexioak\n\n- Mezu elektronikoak kanpoko iturrietako irudiak baditu, Email to PDF converter-ek irudiak deskargatuko ditu, kanpoko konexioak behar direlarik\n- Oraingo bertsioak ez du Nextcloud-en proxy konfigurazioa kontuan hartzen, baina sistemaren lehenetsia jarraitu beharko luke"
},
"nplurals=2; plural=(n != 1);");
