OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "E-posta ikustailea",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Gaitu proc_open php funtzioa posta elektronikotik pdf-ra bihurgailua exekutatzeko.",
    "Java is required to run the email-to-pdf converter." : "Java beharrezkoa da posta elektronikotik pdf-ra bihurgailua exekutatzeko.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Mesedez, instalatu https://github.com/nickrussler/email-to-pdf-converter eta ezarri bidea  `%s` bidez",
    "View .msg and .eml files" : "Ikusi .msg eta .eml fitxategiak",
    "<h4>Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.</h4>\n\n<h5>Requirements</h5>\n<ul>\n\t<li>Nextcloud 28 or newer</li>\n\t<li>PDF Viewer for Nextcloud</li>\n\t<li>PHP proc_open</li>\n\t<li>OpenJDK</li>\n\t<li>wkhtmltopdf (https://wkhtmltopdf.org/)</li>\n\t<li>Email to PDF Converter (https://github.com/nickrussler/email-to-pdf-converter)</li>\n</ul>\n\n<h5>Installation</h5>\n<ul>\n\t<li>Download and enable files_emailviewer</li>\n\t<li>Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it</li>\n\t<li>Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`</li>\n\t<li>Upload a .msg or .eml file and view it directly in Nextcloud 🙌</li>\n</ul>\n\n<h5>Outgoing connections</h5>\n<ul>\n\t<li>If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections</li>\n\t<li>The current version does not consider Nextcloud's proxy configuration but should follow the system default</li>\n</ul>" : "\t<h4>E-posta Ikustaileak Email to PDF Converter bikaina Nextcloud-en integratzen du, .msg eta .eml fitxategiak ikusteko aukera emanez.</h4>\n\n<h5>Eskakizunak</h5>\n<ul>\n<li>Nextcloud 28 edo berriagoa</li>\n<li>Nextcloud-erako PDF Ikustallea</li>\n<li>PHP proc_open</li>\n<li>OpenJDK</li>\n <li>wkhtmltopdf https://wkhtmltopdf.org/)</li>\n<li>E-posta-tik PDFra bihurgailua (https://github.com/nickrussler/email-to-pdf-converter)</li>\n\t\n</ul>Instalazioa</h5>\n<ul>\n<li>Deskargatu eta gaitu files_emailviewer</li>\n<li>Gorde Email to PDF Converter-en kopia bat zerbitzarian, Nextcloud-ek horretarako sarbidea duela ziurtatuz</li>\n<li>Ezarri Posta elektronikotik PDFra bihurgailurako bidea `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar-en  files_emailviewer binary_path`-en bidez</li>\n<li>Kargatu .msg edo .eml fitxategi bat eta ikusi zuzenean Nextcloud-en 🙌</li>\n</ul>\n\n<h5>Irteerako konexioak</h5>\n<ul>\n<li>Mezu elektronikoak kanpoko iturrietako irudiak baditu, E-postatik PDFra bihurgailuak irudiak deskargatuko ditu, kanpoko konexioak eskatuz</li>\n<li>Uneko bertsioak ez du Nextcloud-en proxy konfigurazioa kontuan hartzen, baina sistemaren lehenetsia jarraitu beharko luke</li>\n</ul>"
},
"nplurals=2; plural=(n != 1);");
