OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "Visionneuse d'e-mail",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Activer la fonction PHP proc_open pour exécuter le convertisseur d’e-mail en PDF.",
    "Java is required to run the email-to-pdf converter." : "Java est requis pour exécuter le convertisseur e-mail-PDF.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Veuillez installer https://github.com/nickrussler/email-to-pdf-converter et définir le chemin via `%s`",
    "View .msg and .eml files" : "Visualiser les fichiers .msg et .eml",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### Email Viewer intègre l'excellent convertisseur d'e-mails en PDF dans Nextcloud, vous permettant d'afficher les fichiers .msg et .eml.#### Configuration requise- Nextcloud 28 ou plus récent- Visionneuse et visionneuse PDF pour Nextcloud- PHP proc_open- [Convertisseur d'e-mails en PDF](https://github.com/nickrussler/email-to-pdf-converter) (nécessite OpenJDK et [wkhtmltopdf](https://wkhtmltopdf.org/))#### Installation- Téléchargez et activez files_emailviewer- Stockez une copie du convertisseur d'e-mails en PDF sur le serveur, en vous assurant que Nextcloud y a accès- Définissez le chemin d'accès au convertisseur d'e-mails en PDF via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`- Téléchargez un fichier .msg ou .eml et affichez-le directement dans Nextcloud 🙌#### Connexions sortantes- Si l'e-mail contient des images provenant de sources externes, le convertisseur d'e-mails en PDF téléchargera les images, nécessitant des connexions externes- La version actuelle ne prend pas en compte la configuration proxy de Nextcloud mais doit suivre la configuration par défaut du système"
},
"nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;");
