OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "Amharcóir Ríomhphoist",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Cumasaigh an fheidhm php proc_open chun an tiontaire ríomhphost-go-pdf a rith.",
    "Java is required to run the email-to-pdf converter." : "Tá gá le Java chun an tiontaire ríomhphost go pdf a rith.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Suiteáil https://github.com/nickrussler/email-to-pdf-converter agus socraigh an chonair trí `%s`",
    "View .msg and .eml files" : "Féach ar chomhaid .msg agus .eml",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 34 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### Comhtháthaíonn Amharcóir Ríomhphoist an Tiontaire Ríomhphoist go PDF den scoth isteach i Nextcloud, rud a chuireann ar do chumas comhaid .msg agus .eml a fheiceáil.\n\n#### Riachtanais\n\n- Nextcloud 34 nó níos nuaí\n- Amharcóir agus Amharcóir PDF do Nextcloud\n- PHP proc_open\n- [Tiontaire Ríomhphoist go PDF](https://github.com/nickrussler/email-to-pdf-converter) (tá OpenJDK agus [wkhtmltopdf](https://wkhtmltopdf.org/) ag teastáil)\n\n#### Suiteáil\n\n- Íoslódáil agus cumasaigh files_emailviewer\n- Stóráil cóip den Tiontaire Ríomhphoist go PDF ar an bhfreastalaí, ag cinntiú go bhfuil rochtain ag Nextcloud air\n- Socraigh an cosán chuig an Tiontaire Ríomhphoist go PDF trí `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Uaslódáil comhad .msg nó .eml agus féach air go díreach i Nextcloud 🙌\n\n#### Naisc Amach\n\n- Má tá íomhánna ó fhoinsí seachtracha sa ríomhphost, íoslódálfaidh an tiontaire Ríomhphoist go PDF na híomhánna, rud a éilíonn naisc sheachtracha\n- Ní chuireann an leagan reatha cumraíocht seachfhreastalaí Nextcloud san áireamh ach ba chóir go leanfadh sé réamhshocrú an chórais"
},
"nplurals=5; plural=(n==1 ? 0 : n==2 ? 1 : n<7 ? 2 : n<11 ? 3 : 4);");
