OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "Visor de correo-e",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Active a función php proc_open para executar o convertedor de correo-e a pdf.",
    "Java is required to run the email-to-pdf converter." : "Precisase de Java para executar o convertedor de correo-e a PDF.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Instale https://github.com/nickrussler/email-to-pdf-converter e defina a ruta mediante «%s»",
    "View .msg and .eml files" : "Ver ficheiros .msg e .eml",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### O Visor de correo-e integra o excelente Convertedor de correo-e a PDF en Nextcloud, permitíndolle ver ficheiros .msg e .eml.\ncorreo\n#### Requisitos\n\n- Nextcloud 28 ou máis recente\n- Visor e Visor de PDF para Nextcloud\n- PHP proc_open\n- [Convertedor de correo-e a PDF](https://github.com/nickrussler/email-to-pdf-converter) (precisa de OpenJDK e de [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Instalación\n\n- Descargue e active files_emailviewer\n- Garde unha copia do Convertedor de correo-e a PDF no servidor, asegurándose de que Nextcloud teña acceso a el\n- Defina a ruta ao Convertedor de correo-e a PDF mediante `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Envíe un ficheiro .msg ou .eml e véxao directamente en Nextcloud 🙌\n\n#### Conexións de saída\n\n- Se o correo-e contén imaxes de fontes externas, o Convertedor de correo-e a PDF descargará as imaxes, precisando de conexións externas\n- A versión actual non considera a configuración do proxy de Nextcloud, mais debería seguir a predeterminada do sistema"
},
"nplurals=2; plural=(n != 1);");
