OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "Preglednik e-pošte",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Omogućite PHP funkciju proc_open kako bi se mogao pokrenuti pretvarač e-pošte u PDF.",
    "Java is required to run the email-to-pdf converter." : "Java je potrebna za pokretanje pretvarača e-pošte u PDF.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Instalirajte https://github.com/nickrussler/email-to-pdf-converter i postavite putanju putem %s.",
    "View .msg and .eml files" : "Pregled .msg i .eml datoteka",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### Preglednik e-pošte eng. Email Viewer integrira izvrstan pretvarač e-pošte u PDF u Nextcloudu, omogućujući pregled .msg i .eml datoteka.\n\n#### Zahtjevi\n\n- Nextcloud 28 ili noviji\n- Viewer i PDF Viewer za Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (zahtjeva OpenJDK i [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Instalacija\n\n- Preuzmite i omogućite files_emailviewer\n- Pohranite kopiju Email to PDF Convertera na poslužitelj i osigurajte da Nextcloud ima pristup\n- Postavite putanju do Email to PDF Convertera pomoću 'occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path'\n- Učitajte .msg ili .eml datoteku i pregledajte je izravno u Nextcloudu 🙌\n\n#### Izlazne veze\n\n-Ako e-poruka sadrži slike iz vanjskih izvora, pretvarač Email to PDF preuzet će slike, što zahtijeva vanjske veze\n- Trenutačna verzija ne uzima u obzir proxy postavke Nextclouda, već koristi zadane postavke sustava"
},
"nplurals=3; plural=n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2;");
