OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "Penampil Email",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Aktifkan fungsi PHP proc_open untuk menjalankan konverter email-ke-PDF.",
    "Java is required to run the email-to-pdf converter." : "Java diperlukan untuk menjalankan konverter email-ke-PDF.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Silakan pasang [https://github.com/nickrussler/email-to-pdf-converter](https://github.com/nickrussler/email-to-pdf-converter) dan tetapkan jalurnya melalui `%s`",
    "View .msg and .eml files" : "Lihat file .msg dan .eml",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### Penampil Email mengintegrasikan Email to PDF Converter yang luar biasa ke Nextcloud, sehingga Anda dapat melihat file .msg dan .eml.\n\n#### Persyaratan\n\n- Nextcloud 28 atau lebih baru\n- Viewer dan PDF Viewer untuk Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (memerlukan OpenJDK dan [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Instalasi\n\n- Unduh dan aktifkan files_emailviewer\n- Simpan salinan Email to PDF Converter di server, pastikan Nextcloud dapat mengaksesnya\n- Tetapkan jalur ke Email to PDF Converter melalui `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Unggah file .msg atau .eml dan lihat langsung di Nextcloud 🙌\n\n#### Koneksi keluar\n\n- Jika email berisi gambar dari sumber eksternal, konverter Email to PDF akan mengunduh gambar tersebut, sehingga memerlukan koneksi eksternal\n- Versi saat ini tidak mempertimbangkan konfigurasi proxy Nextcloud, tetapi seharusnya mengikuti default sistem"
},
"nplurals=1; plural=0;");
