OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "이메일 뷰어",
    "Enable the php function proc_open to run the email-to-pdf converter." : "email-to-pdf 변환기를 실행하기 위해서 php 함수 proc_open 을 활성화하십시오.",
    "Java is required to run the email-to-pdf converter." : "email-to-pdf 변환기를 실행하기 위해서 Java가 필요합니다.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "https://github.com/nickrussler/email-to-pdf-converter 를 설치하고 경로를 `%s` 로 설정합니다.",
    "View .msg and .eml files" : ".msg 와 .eml 파일을 표시합니다.",
    "<h4>Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.</h4>\n\n<h5>Requirements</h5>\n<ul>\n\t<li>Nextcloud 28 or newer</li>\n\t<li>PDF Viewer for Nextcloud</li>\n\t<li>PHP proc_open</li>\n\t<li>OpenJDK</li>\n\t<li>wkhtmltopdf (https://wkhtmltopdf.org/)</li>\n\t<li>Email to PDF Converter (https://github.com/nickrussler/email-to-pdf-converter)</li>\n</ul>\n\n<h5>Installation</h5>\n<ul>\n\t<li>Download and enable files_emailviewer</li>\n\t<li>Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it</li>\n\t<li>Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`</li>\n\t<li>Upload a .msg or .eml file and view it directly in Nextcloud 🙌</li>\n</ul>\n\n<h5>Outgoing connections</h5>\n<ul>\n\t<li>If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections</li>\n\t<li>The current version does not consider Nextcloud's proxy configuration but should follow the system default</li>\n</ul>" : "<h4>이메일 뷰어는 훌륭한 Email to PDF 변환기를 Nextcloud에 통합하여 .msg와 .eml 을 표시할 수 있게 합니다.</h4>\n\n<h5>요구사항</h5>\n<ul>\n\t<li>Nextcloud 28 혹은 이후 최신</li>\n\t<li>Nextcloud 용 PDF 뷰어</li>\n\t<li>PHP proc_open</li>\n\t<li>OpenJDK</li>\n\t<li>wkhtmltopdf (https://wkhtmltopdf.org/)</li>\n\t<li>Email to PDF 변환기 (https://github.com/nickrussler/email-to-pdf-converter)</li>\n</ul>\n\n<h5>설치</h5>\n<ul>\n\t<li>다운로드 후 files_emailviewer 활성화</li>\n\t<li>Email to PDF 변환기를 서버에 저장 후, Nextcloud가 접근할 수 있게 설정</li>\n\t<li>Email to PDF 변환기를 다음 명령어로 설정  `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`</li>\n\t<li>.msg나 .eml 파일을 업로드하고 Nextcloud에서 바로 확인 🙌</li>\n</ul>\n\n<h5>외부 연결</h5>\n<ul>\n\t<li>이메일이 외부 소스로 부터 이미지를 포함하고 있다면, Email to PDF 변환기가 이미지를 다운로드 받으며, 이 동작에 외부 연결이 필요합니다.</li>\n\t<li>현재 버전은 Nextcloud의 프록시 설정이 반영되지 않지만 시스템 기본을 따릅니다.</li>\n</ul>"
},
"nplurals=1; plural=0;");
