OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "이메일 뷰어",
    "Enable the php function proc_open to run the email-to-pdf converter." : "email-to-pdf 변환기를 실행하기 위해서 php 함수 proc_open 을 활성화하십시오.",
    "Java is required to run the email-to-pdf converter." : "email-to-pdf 변환기를 실행하기 위해서 Java가 필요합니다.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "https://github.com/nickrussler/email-to-pdf-converter 를 설치하고 경로를 `%s` 로 설정합니다.",
    "View .msg and .eml files" : ".msg 와 .eml 파일을 표시합니다.",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### 이메일 뷰어는 훌륭한 Email to PDF 변환기를 Nextcloud에 통합하여 .msg 와 .eml 파일을 볼 수 있습니다.\n\n#### 요구사항\n\n- Nextcloud 28 혹은 이상\n- Nextcloud 용 Viewer 와 PDF Viewer\n- PHP proc_open\n- [Email to PDF 변환기](https://github.com/nickrussler/email-to-pdf-converter) (OpenJDK 와 [wkhtmltopdf](https://wkhtmltopdf.org/) 필요)\n\n#### 설치\n\n- 다운로드 후 files_emailviewer 를 활성화합니다\n- Email to PDF 변환기 사본을 서버에 저장하고, Nextcloud에서 접근할 수 있도록 합니다\n- 다음을 통하여 Email to PDF Converter 경로를 지정합니다: `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- .msg 나 .eml 파일을 업로드하고 Nextcloud 에서 바로 확인합니다 🙌\n\n#### 외부 연결\n\n- 이메일이 외부 소스로 부터 이미지를 포함하고 있다면, Email to PDF 변환기는 이미지를 다운로드 할 것이고, 외부 연결을 필요합니다\n- 현재 버전은 Nextcloud의 프록시 설정을 고려하지 않지만 시스템 기본 설정을 따릅니다"
},
"nplurals=1; plural=0;");
