OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "Leitor de Email",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Habilite a função php proc_open para executar o conversor email-para-pdf.",
    "Java is required to run the email-to-pdf converter." : "O Java é necessário para executar o conversor email-para-pdf.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Por favor instale https://github.com/nickrussler/email-to-pdf-converter e configure seu caminho usando `%s`",
    "View .msg and .eml files" : "Ver arquivos .msg e .eml",
    "<h4>Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.</h4>\n\n<h5>Requirements</h5>\n<ul>\n\t<li>Nextcloud 28 or newer</li>\n\t<li>PDF Viewer for Nextcloud</li>\n\t<li>PHP proc_open</li>\n\t<li>OpenJDK</li>\n\t<li>wkhtmltopdf (https://wkhtmltopdf.org/)</li>\n\t<li>Email to PDF Converter (https://github.com/nickrussler/email-to-pdf-converter)</li>\n</ul>\n\n<h5>Installation</h5>\n<ul>\n\t<li>Download and enable files_emailviewer</li>\n\t<li>Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it</li>\n\t<li>Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`</li>\n\t<li>Upload a .msg or .eml file and view it directly in Nextcloud 🙌</li>\n</ul>\n\n<h5>Outgoing connections</h5>\n<ul>\n\t<li>If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections</li>\n\t<li>The current version does not consider Nextcloud's proxy configuration but should follow the system default</li>\n</ul>" : "<h4>O Email Viewer integra o excelente Email to PDF Converter ao Nextcloud, permitindo que você visualize arquivos .msg e .eml.</h4>\n\n<h5>Requisitos</h5>\n<ul>\n\t<li>NextCloud 28 ou mais novo</li>\n\t<li>Visualizador de PDF para NextCloud</li>\n\t<li>PHP proc_open</li>\n\t<li>OpenJDK</li>\n\t<li>wkhtmltopdf (https://wkhtmltopdf.org/)</li>\n\t<li>E-mail para pdf conversor (https://github.com/nickrussler/email-to-pdf-converter)</li>\n</ul>\n\n<h5>Instalação</h5>\n<ul>\n\t<li>Baixar e ativar o arquivo_emailViewer</li>\n\t<li>Armazene uma cópia do e -mail para o conversor PDF no servidor, garantindo que o NextCloud tenha acesso a ele</li>\n\t<li>Defina o caminho para enviar um email para o conversor PDF via `occ Config: App: Set --Value /opt/emailConverter-3.0.0-all.jar files_emailViewer binary_path`</li>\n\t<li>Faça upload de um arquivo .msg ou .eml e visualize -o diretamente no NextCloud 🙌</li>\n</ul>\n\n<h5>Conexões de saída</h5>\n<ul>\n\t<li>Se o e-mail contiver imagens de fontes externas, o conversor de e-mail para PDF fará o download das imagens, exigindo conexões externas</li>\n\t<li>A versão atual não considera a configuração de proxy do NextCloud, mas deve seguir o padrão do sistema</li>\n</ul>"
},
"nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;");
