OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "Prehliadač e-mailov",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Povoľte funkciu php proc_open na spustenie konvertora e-mailu na pdf.",
    "Java is required to run the email-to-pdf converter." : "Na spustenie konvertora e-mailu na pdf je potrebná Java.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Nainštalujte https://github.com/nickrussler/email-to-pdf-converter a nastavte cestu cez `%s`",
    "View .msg and .eml files" : "Zobrazenie súborov .msg a .eml",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### Prehliadač e-mailov integruje vynikajúci prevodník e-mailov do PDF do Nextcloud, ktorý vám umožňuje prezerať súbory .msg a .eml.\n\n#### Požiadavky\n\n- Nextcloud 28 alebo novší\n- Webový prehliadač a prehliadač PDF pre Nextcloud\n- PHP proc_open\n- [Prevodník E-mailu na PDF](https://github.com/nickrussler/email-to-pdf-converter) (vyžaduje OpenJDK a [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Inštalácia\n\n- Stiahnite si a povoľte files_emailviewer\n- Uložte kópiu e-mailu do PDF Converter na serveri, aby ste zabezpečili, že Nextcloud má k nemu prístup\n- Nastavte cestu k e-mailu na prevodník PDF cez `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binárna_cesta`\n- Nahrajte súbor .msg alebo .eml a zobrazte si ho priamo v Nextcloud 🙌\n\n#### Odchádzajúce spojenia\n\n- Ak e-mail obsahuje obrázky z externých zdrojov, konvertor e-mailu na PDF obrázky stiahne, čo si vyžaduje externé pripojenie\n- Aktuálna verzia nezohľadňuje konfiguráciu proxy servera Nextcloud, ale mala by sa riadiť predvoleným nastavením systému"
},
"nplurals=4; plural=(n % 1 == 0 && n == 1 ? 0 : n % 1 == 0 && n >= 2 && n <= 4 ? 1 : n % 1 != 0 ? 2: 3);");
