OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "Приказивач е-мејла",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Укључује php функцију proc_open за покретање и-мејл-у-pdf конвертора.",
    "Java is required to run the email-to-pdf converter." : "За покретање и-мејл-у-pdf конвертора је неопходна Јава.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Молимо вас да инсталирате https://github.com/nickrussler/email-to-pdf-converter и поставите путању преко `%s`",
    "View .msg and .eml files" : "Приказ .msg и .eml фајлова",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### И-мејл Приказивач интегрише изврсни Email to PDF Converter у Nextcloud, чиме добијате могућност да приказујете .msg и .eml фајлове.\n\n#### Захтеви\n\n- Nextcloud 28 или новији\n- Приказивач и PDF приказивач за Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (захтева OpenJDK и [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Инсталација\n\n- Преузмите и укључите files_emailviewer\n- Сачувајте на серверу копију програма Email to PDF Converter и обезбедите да Nextcloud има приступ тој локацији\n- Поставите путању до Email to PDF Converter помоћу `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Отпремите .msg или .eml фајл и директно га прикажите у Nextcloud 🙌\n\n#### Одлазне везе\n\n- Ако и-мејл садржи слике са спољашњох извора, Email to PDF converter ће да их преузе, тако да су неопходне спољашње везе\n- Текућа верзија не узима у обзир прокси конфигурацију Nextcloud инстанце, али би требало да следи подразумевано системско подешавање"
},
"nplurals=3; plural=(n%10==1 && n%100!=11 ? 0 : n%10>=2 && n%10<=4 && (n%100<10 || n%100>=20) ? 1 : 2);");
