OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "E-postvisare",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Aktivera PHP-funktionen proc_open för att köra konverteraren från e-post till PDF.",
    "Java is required to run the email-to-pdf converter." : "Java krävs för att köra konverteraren från e-post till PDF.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Installera https://github.com/nickrussler/email-to-pdf-converter och ställ in sökvägen via `%s`",
    "View .msg and .eml files" : "Visa .msg- och .eml-filer",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### E-postvisaren integrerar den utmärkta Email to PDF Converter i Nextcloud så att du kan visa .msg- och .eml-filer.\n\n#### Krav\n\n- Nextcloud 28 eller senare\n- Viewer och PDF Viewer för Nextcloud\n- PHP-funktionen proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (kräver OpenJDK och [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Hämta och aktivera files_emailviewer\n- Spara en kopia av Email to PDF Converter på servern och se till att Nextcloud har åtkomst till den\n- Ange sökvägen till Email to PDF Converter med `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Ladda upp en .msg- eller .eml-fil och visa den direkt i Nextcloud 🙌\n\n#### Utgående anslutningar\n\n- Om e-postmeddelandet innehåller bilder från externa källor hämtar Email to PDF Converter bilderna, vilket kräver externa anslutningar\n- Den aktuella versionen tar inte hänsyn till Nextclouds proxykonfiguration utan bör följa systemets standardinställning"
},
"nplurals=2; plural=(n != 1);");
