OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "E-posta görüntüleyici",
    "Enable the php function proc_open to run the email-to-pdf converter." : "email-to-pdf dönüştürücü için proc_open php işlevini kullanıma alın.",
    "Java is required to run the email-to-pdf converter." : "email-to-pdf dönüştürücü için Java gereklidir.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Lütfen https://github.com/nickrussler/email-to-pdf-converter uygulamasını kurun ve `%s` ile yolu ayarlayın",
    "View .msg and .eml files" : ".msg ve .eml dosyalarını görüntüle",
    "<h4>Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.</h4>\n\n<h5>Requirements</h5>\n<ul>\n\t<li>Nextcloud 28 or newer</li>\n\t<li>PDF Viewer for Nextcloud</li>\n\t<li>PHP proc_open</li>\n\t<li>OpenJDK</li>\n\t<li>wkhtmltopdf (https://wkhtmltopdf.org/)</li>\n\t<li>Email to PDF Converter (https://github.com/nickrussler/email-to-pdf-converter)</li>\n</ul>\n\n<h5>Installation</h5>\n<ul>\n\t<li>Download and enable files_emailviewer</li>\n\t<li>Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it</li>\n\t<li>Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`</li>\n\t<li>Upload a .msg or .eml file and view it directly in Nextcloud 🙌</li>\n</ul>\n\n<h5>Outgoing connections</h5>\n<ul>\n\t<li>If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections</li>\n\t<li>The current version does not consider Nextcloud's proxy configuration but should follow the system default</li>\n</ul>" : "<h4>E-posta görüntüleyici, mükemmel E-posta - PDF dönüştürücüyü Nextcloud ile bütünleştirerek .msg ve .eml dosyalarını görüntülemenizi sağlar.</h4>\n\n<h5>Gereksinimler</h5>\n<ul>\n\t<li>Nextcloud 28 ya da üzeri</li>\n\t<li>Nextcloud için PDF görüntüleyici</li>\n\t<li>PHP proc_open işlevi</li>\n\t<li>OpenJDK</li>\n\t<li>wkhtmltopdf (https://wkhtmltopdf.org/)</li>\n\t<li>E-posta - PDF dönüştürücü (https://github.com/nickrussler/email-to-pdf-converter)</li>\n</ul>\n\n<h5>Kurulum</h5>\n<ul>\n\t<li>files_emailviewer uygulamasını indirin ve kullanıma alın</li>\n\t<li>E-posta - PDF dönüştürücünün bir kopyasını sunucuda tutun ve buna Nextcloud tarafından erişebildiğinden emin olun</li>\n\t<li>`occ config:app:set --value ile E-posta - PDF dönüştürücünün yolunu ayarlayın /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`</li>\n\t<li>Bir .msg veya .eml dosyası yükleyin ve doğrudan Nextcloud içinde görüntüleyin 🙌</li>\n</ul>\n\n<h5>Giden bağlantılar</h5>\n<ul>\n\t<li>E-postada dış kaynaklardan gelen görseller bulunuyorsa, E-posta - PDF dönüştürücü uygulamasının dış bağlantılara erişerek görselleri indirmesi gerekir</li>\n\t<li>Geçerli sürüm Nextcloud vekil sunucu yapılandırmasını dikkate almaz ancak sistem varsayılan ayarlarına uymalıdır</li>\n</ul>"
},
"nplurals=2; plural=(n > 1);");
