OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "ئېلخەت كۆرگۈچى",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Php ئىقتىدارىنى proc_open نى قوزغىتىپ ئېلېكترونلۇق خەتتىن pdf ئايلاندۇرغۇچنى ئىجرا قىلىڭ.",
    "Java is required to run the email-to-pdf converter." : "Java دىن ئېلېكترونلۇق خەتتىن pdf ئايلاندۇرغۇچنى ئىجرا قىلىش تەلەپ قىلىنىدۇ.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "https://github.com/nickrussler/email-to-pdf-converter نى قاچىلاپ ،`%s` ئارقىلىق يول بەلگىلەڭ.",
    "View .msg and .eml files" : ".Mg ۋە .eml ھۆججىتىنى كۆرۈڭ",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### ئېلخەت كۆرۈش قورالى ئېسىل ئېلخەتنى PDF غا ئايلاندۇرغۇچنى Nextcloud غا بىرلەشتۈرۈپ، سىزگە .msg ۋە .eml ھۆججەتلىرىنى كۆرۈش ئىمكانىيىتىنى بېرىدۇ.\n\n#### تەلەپلەر\n\n- Nextcloud 28 ياكى ئۇنىڭدىن يېڭى نەشرى\n- Nextcloud ئۈچۈن كۆرگۈچ ۋە PDF كۆرگۈچ\n- PHP proc_open\n- [PDF غا ئېلخەت ئايلاندۇرغۇچ](https://github.com/nickrussler/email-to-pdf-converter) (OpenJDK ۋە [wkhtmltopdf](https://wkhtmltopdf.org/)) تەلەپ قىلىدۇ\n\n#### قاچىلاش\n\n- files_emailviewer نى چۈشۈرۈپ قوزغىتىڭ\n- Email to PDF ئايلاندۇرغۇچنىڭ كۆچۈرمىسىنى مۇلازىمېتىردا ساقلاڭ، Nextcloud نىڭ ئۇنىڭغا كىرىشىگە كاپالەتلىك قىلىڭ\n- `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path` ئارقىلىق Email to PDF ئايلاندۇرغۇچنىڭ يولىنى تەڭشەڭ\n- .msg ياكى .eml ھۆججىتىنى يۈكلەڭ ۋە ئۇنى بىۋاسىتە Nextcloud دا كۆرۈڭ 🙌\n\n#### چىقىش ئۇلىنىشلىرى\n\n- ئەگەر ئېلخەتتە سىرتقى مەنبەلەردىن كەلگەن رەسىملەر بولسا، Email to PDF ئايلاندۇرغۇچ چۈشۈرىدۇ رەسىملەر، سىرتقى ئۇلىنىشنى تەلەپ قىلىدۇ\n- نۆۋەتتىكى نەشرى Nextcloud نىڭ ۋاكالەتچى تەڭشىكىنى كۆزدە تۇتمايدۇ، ئەمما سىستېما سۈكۈتتىكى ھالىتىگە ئەگىشىشى كېرەك."
},
"nplurals=2; plural=(n != 1);");
