OC.L10N.register(
    "files_emailviewer",
    {
    "Email Viewer" : "Elektron pochtani ko'rish dasturi",
    "Enable the php function proc_open to run the email-to-pdf converter." : "Elektron pochtadan PDF-ga o'zgartirgichni ishga tushirish uchun proc_open php funksiyasini yoqing.",
    "Java is required to run the email-to-pdf converter." : "E-pochtadan pdf-ga o'zgartirgichni ishga tushirish uchun Java talab qilinadi.",
    "Please install https://github.com/nickrussler/email-to-pdf-converter and set the path via `%s`" : "Iltimos, https://github.com/nickrussler/email-to-pdf-converter ni oʻrnating va “%s” orqali yoʻlni belgilang.",
    "View .msg and .eml files" : ".msg va .eml fayllarini ko'ring",
    "### Email Viewer integrates the excellent Email to PDF Converter into Nextcloud, enabling you to view .msg and .eml files.\n\n#### Requirements\n\n- Nextcloud 28 or newer\n- Viewer and PDF Viewer for Nextcloud\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (requires OpenJDK and [wkhtmltopdf](https://wkhtmltopdf.org/))\n\n#### Installation\n\n- Download and enable files_emailviewer\n- Store a copy of the Email to PDF Converter on the server, ensuring that Nextcloud has access to it\n- Set the path to Email to PDF Converter via `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path`\n- Upload a .msg or .eml file and view it directly in Nextcloud 🙌\n\n#### Outgoing connections\n\n- If the email contains images from external sources, the Email to PDF converter will download the images, requiring external connections\n- The current version does not consider Nextcloud's proxy configuration but should follow the system default" : "### Email Viewer mukammal Email to PDF Converter-ni Nextcloud-ga birlashtiradi, bu sizga .msg va .eml fayllarini ko'rish imkonini beradi.\n\n#### Talablar\n\n- Nextcloud 28 yoki undan yangiroq\n- NextCloud uchun Viewer va PDF Viewer\n- PHP proc_open\n- [Email to PDF Converter](https://github.com/nickrussler/email-to-pdf-converter) (OpenJDK va [wkhtmltopdf](https://wkhtmltopdf.org/) talab qilinadi)\n\n#### O'rnatish\n\n- files_emailviewer-ni yuklab oling va yoqing\n- Email to PDF Converter nusxasini serverda saqlang, Nextcloud-ning unga kirishiga ishonch hosil qiling.\n- `occ config:app:set --value /opt/emailconverter-3.0.0-all.jar files_emailviewer binary_path` orqali PDF Converterga elektron pochta manzilini o'rnating.\n- .msg yoki .eml faylini yuklang va uni bevosita Nextcloud orqali koʻring 🙌\n\n#### Chiquvchi ulanishlar\n\n- Agar e-pochtada tashqi manbalardan olingan tasvirlar bo'lsa, Email to PDF konvertori tashqi ulanishlarni talab qiladigan rasmlarni yuklab oladi.\n- Joriy versiya Nextcloud proksi-server konfiguratsiyasini hisobga olmaydi, lekin tizim standartiga amal qilishi kerak"
},
"nplurals=1; plural=0;");
